### ISSUE TITLE
Use TEOS-10 as a submodule and drop all home made density related code.

### ISSUE THREAD

**Issue by bolding** [gotm-model/code#17]
The density is relative straigh forward - but we should also investigate the use of the TEOS10 [NN](https://github.com/TEOS-10/GSW-Fortran/blob/master/toolbox/gsw_nsquared.f90).

**Comment by adolfstips** [comment]
Hi Karsten,

I intend to support TEOS10 implementation (but most likely more to the end of 2021)
And for sure, when this is done, then ALL the GSW library must be used, which is critical for consistency.

Further I wonder, why are there no proposals for 3rd order turbulence schemes, to
get a grip on countergradient fluxes? Nobody working on this?

Ciao Adolf

**Comment by lumlauf** [comment]
I'm happy to contribute. The main difficulty will be to make the TEOS10 version of NN work for zoomed grids, and to convert the surface heat fluxes to what is needed for a transport equation for conservative temperature. I have some ideas how this can be done. Also the output needs to be modified to account for the modified and (perhaps) added new TEOS-10 variables. 

Lars

**Comment by bolding** [comment]
please follow
https://github.com/gotm-model/code/issues/25
