### ISSUE TITLE
Restart.nc file name as a parameter

### ISSUE THREAD

**Issue by shajar007** [gotm-model/code#29]
Hi, I would like to request - suggest an enhancement:
I'm using GOTM within QWET.
Currently, each run produces a "restart.nc" file. If you set in gotm.yaml, restart=true, than values in restart is used as initial conditions. However, the restart.nc file name is hardcoded and not a parameter. This means that every time you run the model with restart=true you get an initial conditions from the last run. I would like to suggest that the file name will be a parameter so you can set constant initial conditions. So I'm thinking of the restart.nc as a more accurate initial conditions (rather than the intended use - for restart). I find it important to set more detailed initial conditions for processes that take a years to stabilize, such as the humus sediment.
If the solution will include the ability of ParSAC to use it - this would be even better (currently parsac does not copy .nc files).

Shajar

**Comment by shajar007** [comment]
Hi Karsten, 
I am using QWET which is a GOTM-FABM-PCLake integration. I'm not sure what version of GOTM is used, but it has lake support.
For physical initial condition, constant values are fine. But for geochemical variables it's not:  sediment humus and inorganic material take about 60 years (in my model) to reach a steady state for their distribution in depth. This affects phosphorus absorption.
I know that parsac is another issue - just a hint for further enhancement if my suggestion will be accepted....
Thanks, Shajar

**Comment by bolding** [comment]
but you can read in depth resolved initial conditions for all state variables - you don't have to start with constant profiles

**Comment by shajar007** [comment]
You mean I can load files with initial conditions? I don't see an option in the fabm.yaml or gotm.yaml to do so.

**Comment by bolding** [comment]
In the namelist age of GOTM it was done in fabm_input.nml - like:
&observations
  variable = 'selma_po_glenamong',
   file = 'glen_po.dat',
   index = 1,
   !constant_value = 1,
   relax_tau = 1e+15,
/

in the YAML age it is described here - https://github.com/fabm-model/fabm/wiki/GOTM - search for Prescribing biogeochemical variables

**Comment by shajar007** [comment]
Great! This solves my need. thanks!
