### ISSUE TITLE
Compile the manual

### ISSUE THREAD

**Issue by bderembl** [gotm-model/code#50]
Hi,
I am trying to compile the manual. It looks like I need an executable or a script called "protex" (see Makefile in doc/).
I found this CTAN package https://ctan.org/tex-archive/web/protex which does not have any executable. Did I miss something?

side question: could it be possible to update the manual on http://gotm.net?

Thank you!

**Comment by bolding** [comment]
Hi

The documentation is outdated and requires serious work to bring up to date. Even if you have protex - the documentation is still out dated.

We have done some preliminary new initiatives - but are far from ready.

Protex is not maintained anymore - and has likely not been for many years. It was a perl-script from Goddard Space Flight Center .

Seems it is still being used - https://wiki.seas.harvard.edu/geos-chem/index.php/Automatic_documentation_with_protex.

Karsten

**Comment by bderembl** [comment]
Thank you. that helps.
The link given in the wiki page does not work but I found this
https://github.com/hannahnesser/geos-chem-ch4/blob/main/doc/protex

but then there are several other issues with the makefile.

Anyway, it is great news if there is a new documentation on its way.
